### ISSUE TITLE
New test failure

### ISSUE THREAD

**Issue by rsrock** [JuliaArrays/FFTViews.jl#11]
Something happened here in the last month. The first test here passes, but the second fails:

```
    @test a[3,trues(9)] == [9,14,19,24,29,34,4,9,14]
    @test a[3,FFTView(trues(9))] == [4,9,14,19,24,29,34,4,9]
```

...with this output:

```
  Expression: a[3, FFTView(trues(9))] == [4, 9, 14, 19, 24, 29, 34, 4, 9]
   Evaluated: [9.0, 14.0, 19.0, 24.0, 29.0, 34.0, 4.0, 9.0, 14.0] == [4, 9, 14, 19, 24, 29, 34, 4, 9]
```

Somehow an off-by-one crept in here when indexing a FFTView with another FFTView (of a boolean array)?

**Comment by timholy** [comment]
Sorry I didn't notice this! Fixed in #14
